### ISSUE TITLE
LightPlatformCodeInsightFixtureTestCase usage isn't working anymore?

### ISSUE THREAD

**Issue by calexHG** [JetBrains/Grammar-Kit#109]
The test suite appears to be b0rked in 2016.1.2 #IU-145.971.

All of GK's tests using LightPlatformCodeInsightFixtureTestCase fail for me after updating.

Output from org.intellij.grammar.BnfFirstNextTest:

	log4j:WARN No appenders could be found for logger (#com.intellij.util.ui.JBUI).
	log4j:WARN Please initialize the log4j system properly.
	log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

	java.lang.NoClassDefFoundError: io/netty/channel/EventLoopGroup

		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:348)
		at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:412)
		at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
		at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:458)
		at com.intellij.idea.IdeaTestApplication.getInstance(IdeaTestApplication.java:54)
		at com.intellij.idea.IdeaTestApplication.getInstance(IdeaTestApplication.java:46)
		at 

-- chop chop, sorry

**Comment by gregsh** [comment]
Just re-add IntelliJ plugin SDK.

**Comment by calexHG** [comment]
Ah, okay. 

Just this moment I decided to take a look at this. At least for these errors, just one library seems to be responsible. Adding "<IDEA>\lib\netty-all-4.1.0.CR7.jar" got it to shut up.

Thanks. Closing..
