### ISSUE TITLE
Standalone (1.4.2) is not working

### ISSUE THREAD

**Issue by paxxux** [JetBrains/Grammar-Kit#134]
Hi,

I tried Grammar-Kit standalone with the versions 1.4.2 and 1.4.0, and the latest available version of light-psi-all.jar (1.4.0) and always receive the same exception shown in the code block. I tried to manually add the correct cglib version to the jar, but other exceptions with other dependencies arise. I have in my working directory the files: grammar-kit.jar, light-psi-all.jar and lang.bnf.

If I try it with manually placing all dependencies (jdom.jar, trove4j.jar, extensions.jar, picocontainer.jar, junit.jar, idea.jar, openapi.jar, util.jar) next to grammar-kit.jar I get something like "ParserDefinition not found".

I am somehow unable to build light-psi-all.jar on my own, because the IDE recognizes the src and gen folders as modules and the run configurations fail. `com.sun.jdi.*` in  `BnfPositionManager` is missing.

It would be great, if you could help me out with a working light-psi-all.jar, or tell me what I did it wrong :-).

```
java -jar grammar-kit.jar output lang.bnf 
java.lang.NoClassDefFoundError: net/sf/cglib/core/ClassGenerator
	at com.intellij.util.InstanceofCheckerGenerator.<clinit>(InstanceofCheckerGenerator.java:37)
	at com.intellij.patterns.ObjectPattern$1.<init>(ObjectPattern.java:43)
	at com.intellij.patterns.ObjectPattern.<init>(ObjectPattern.java:42)
	at com.intellij.patterns.TreeElementPattern.<init>(TreeElementPattern.java:37)
	at com.intellij.patterns.PsiElementPattern.<init>(PsiElementPattern.java:42)
	at com.intellij.patterns.PsiElementPattern$Capture.<init>(PsiElementPattern.java:358)
	at com.intellij.patterns.PlatformPatterns.psiElement(PlatformPatterns.java:62)
	at org.intellij.grammar.psi.impl.BnfStringRefContributor.registerReferenceProviders(BnfStringRefContributor.java:48)
	at org.intellij.grammar.psi.impl.BnfStringImpl.<clinit>(BnfStringImpl.java:51)
	at org.intellij.grammar.psi.BnfTypes$Factory.createElement(BnfTypes.java:127)
	at org.intellij.grammar.BnfParserDefinition.createElement(BnfParserDefinition.java:87)
	at com.intellij.psi.impl.source.tree.CompositeElement.createPsiNoLock(CompositeElement.java:818)
	at com.intellij.psi.impl.source.tree.CompositeElement.getPsi(CompositeElement.java:790)
	at com.intellij.psi.impl.source.SourceTreeToPsiMap.treeElementToPsi(SourceTreeToPsiMap.java:30)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getNextSibling(SharedImplUtil.java:61)
	at com.intellij.psi.impl.source.tree.LeafPsiElement.getNextSibling(LeafPsiElement.java:82)
	at com.intellij.psi.impl.PsiElementBase.findChildByClass(PsiElementBase.java:301)
	at org.intellij.grammar.psi.impl.BnfListEntryImpl.getLiteralExpression(BnfListEntryImpl.java:57)
	at org.intellij.grammar.generator.ParserGeneratorUtil.getAttributeValue(ParserGeneratorUtil.java:141)
	at org.intellij.grammar.psi.impl.BnfFileImpl.calcAttributeValues(BnfFileImpl.java:180)
	at org.intellij.grammar.psi.impl.BnfFileImpl.access$200(BnfFileImpl.java:47)
	at org.intellij.grammar.psi.impl.BnfFileImpl$3.compute(BnfFileImpl.java:70)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at org.intellij.grammar.psi.impl.BnfFileImpl.findAttributeInfo(BnfFileImpl.java:109)
	at org.intellij.grammar.psi.impl.BnfFileImpl.findAttributeValue(BnfFileImpl.java:102)
	at org.intellij.grammar.generator.ParserGeneratorUtil.getRootAttribute(ParserGeneratorUtil.java:112)
	at org.intellij.grammar.generator.ParserGeneratorUtil.getRootAttribute(ParserGeneratorUtil.java:108)
	at org.intellij.grammar.generator.GenOptions.<init>(GenOptions.java:49)
	at org.intellij.grammar.generator.ParserGenerator.<init>(ParserGenerator.java:107)
	at org.intellij.grammar.Main.main(Main.java:77)
Caused by: java.lang.ClassNotFoundException: net.sf.cglib.core.ClassGenerator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 33 more
```

Best Regards

**Comment by jvolkman** [comment]
If you place the jars individually, they need to be in a "lib" directory alongside grammar-kit.jar. You can see the classpath in https://github.com/JetBrains/Grammar-Kit/blob/master/resources/META-INF/MANIFEST.MF

**Comment by paxxux** [comment]
Hi,

Thanks for the hint. This resolved a couple of exceptions, but now I get:

```
java -jar grammar-kit.jar output lang.bnf 
java.lang.NoSuchMethodError: com.intellij.openapi.application.ApplicationManager.setApplication(Lcom/intellij/openapi/application/Application;Lcom/intellij/openapi/util/Getter;Lcom/intellij/openapi/Disposable;)V
	at org.intellij.grammar.LightPsi$Init.initApplication(LightPsi.java:299)
	at org.intellij.grammar.LightPsi$Init.initPsiFileFactory(LightPsi.java:253)
	at org.intellij.grammar.LightPsi$MyParsing.<init>(LightPsi.java:183)
	at org.intellij.grammar.LightPsi.<clinit>(LightPsi.java:99)
	at org.intellij.grammar.Main.main(Main.java:64)

```
There is still something missing (com.intellij.openapi.application.ApplicationManager is not in openapi.jar; /com/intellij/application just contains a package "options")

Thanks for your answer!

Best Regards

**Comment by jvolkman** [comment]
Sounds like maybe the classpath entry in the manifest is stale. You can try this as a workaround:

$ java -cp 'grammar-kit.jar:<intellij-directory>/lib/*' org.intellij.grammar.Main <output-dir> <bnf-file>

**Comment by paxxux** [comment]
This raises the same error :

```
java -cp 'grammar-kit.jar:/lib/*' org.intellij.grammar.Main output lang.bnf 
java.lang.NoSuchMethodError: com.intellij.openapi.application.ApplicationManager.setApplication(Lcom/intellij/openapi/application/Application;Lcom/intellij/openapi/util/Getter;Lcom/intellij/openapi/Disposable;)V
    at org.intellij.grammar.LightPsi$Init.initApplication(LightPsi.java:299)
    at org.intellij.grammar.LightPsi$Init.initPsiFileFactory(LightPsi.java:253)
    at org.intellij.grammar.LightPsi$MyParsing.<init>(LightPsi.java:183)
    at org.intellij.grammar.LightPsi.<clinit>(LightPsi.java:99)
    at org.intellij.grammar.Main.main(Main.java:64)
```

**Comment by jvolkman** [comment]
Whoops, github stripped out part of my past message. That should be:
`$ java -cp 'grammar-kit.jar:<path-to-intellij>/lib/*' org.intellij.grammar.Main`

where `<path-to-intellij>` is your intellij installation directory.

**Comment by paxxux** [comment]
This does not work either :-(

The same error message arises.

**Comment by paxxux** [comment]
Hi,

I made a mistake with my last statements, openapi.jar does contain com.intellij.openapi.application.ApplicationManager (I looked in the wrong package com.intellij.application.*). Which is coherent with the error message (NoSuchMethod and not ClassNotFound). Here the `setApplication(...)` of `com.intellij.openapi.application.ApplicationManager`
```
public static void setApplication(@NotNull Application instance, @NotNull Disposable parent) ;

public static void setApplication(@NotNull Application instance,
                                    @NotNull Getter<FileTypeRegistry> fileTypeRegistryGetter,
                                    @NotNull Disposable parent);
```

And here again the corresponding error
```
java.lang.NoSuchMethodError: com.intellij.openapi.application.ApplicationManager.setApplication(Lcom/intellij/openapi/application/Application;Lcom/intellij/openapi/util/Getter;Lcom/intellij/openapi/Disposable;)V
    at org.intellij.grammar.LightPsi$Init.initApplication(LightPsi.java:299)
    at org.intellij.grammar.LightPsi$Init.initPsiFileFactory(LightPsi.java:253)
    at org.intellij.grammar.LightPsi$MyParsing.<init>(LightPsi.java:183)
    at org.intellij.grammar.LightPsi.<clinit>(LightPsi.java:99)
    at org.intellij.grammar.Main.main(Main.java:64)
```

Best regards

**Comment by paxxux** [comment]
Well I was able to create the parser in standalone. I had to remove com.intellij.* from light-psi-all.jar and use the version from gradle of the Grammar-Kit project in my lib folder. Also I had to add guava to the lib folder. So I needed the light-psi-all.jar with modifications and the lib folder.
