### ISSUE TITLE
"Live preview" read-only

### ISSUE THREAD

**Issue by azrdev** [JetBrains/Grammar-Kit#148]
I installed grammar-kit on IDEA 2016.2.5 from settings > plugins. At first it worked as advertised, then somehow it stopped being editable. i.e. Live preview tab opens, but I cannot type or paste in there. Doesn't show line numbers either, if that matters.

Update to IDEA 2016.3 and update of Grammar-kit didn't help. Removing `~/.IdeaIC2016.3` and then installing Grammar-kit again didn't help, either.

Maybe this backtrace is relevant, it occurs multiple times in `~/.IdeaIC2016.3/system/log/idea.log`:

~~~
2016-12-21 16:16:13,042 [ 516677]  ERROR - penapi.actionSystem.impl.Utils - IntelliJ IDEA 2016.3  Build #IC-163.7743.44 
2016-12-21 16:16:13,042 [ 516677]  ERROR - penapi.actionSystem.impl.Utils - JDK: 1.8.0_112 
2016-12-21 16:16:13,042 [ 516677]  ERROR - penapi.actionSystem.impl.Utils - VM: OpenJDK 64-Bit Server VM 
2016-12-21 16:16:13,042 [ 516677]  ERROR - penapi.actionSystem.impl.Utils - Vendor: Oracle Corporation 
2016-12-21 16:16:13,042 [ 516677]  ERROR - penapi.actionSystem.impl.Utils - OS: Linux 
2016-12-21 16:16:13,042 [ 516677]  ERROR - penapi.actionSystem.impl.Utils - Last Action: EditorPaste 
2016-12-21 16:16:13,045 [ 516680]  ERROR - penapi.actionSystem.impl.Utils - update failed for AnAction with ID=ExternalJavaDoc 
java.lang.NullPointerException
        at org.intellij.grammar.parser.GeneratedParserUtilBase$ErrorState.addExpected(GeneratedParserUtilBase.java:952)
        at org.intellij.grammar.parser.GeneratedParserUtilBase$ErrorState.getExpectedText(GeneratedParserUtilBase.java:938)
        at org.intellij.grammar.parser.GeneratedParserUtilBase.reportError(GeneratedParserUtilBase.java:753)
        at org.intellij.grammar.parser.GeneratedParserUtilBase.exit_section_impl_(GeneratedParserUtilBase.java:604)
        at org.intellij.grammar.parser.GeneratedParserUtilBase.exit_section_(GeneratedParserUtilBase.java:516)
        at org.intellij.grammar.livePreview.LivePreviewParser.parse(LivePreviewParser.java:90)
        at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:88)
        at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:49)
        at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:192)
        at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:240)
        at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:39)
        at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
        at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:836)
        at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:515)
        at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:472)
        at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.tryOffset(InjectedLanguageUtil.java:383)
        at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.findInjectedElementNoCommit(InjectedLanguageUtil.java:369)
        at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.findInjectedPsiNoCommit(InjectedLanguageUtil.java:272)
        at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.getEditorForInjectedLanguageNoCommit(InjectedLanguageUtil.java:180)
        at com.intellij.openapi.fileEditor.impl.text.TextEditorPsiDataProvider.getData(TextEditorPsiDataProvider.java:62)
        at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.getData(FileEditorManagerEx.java:176)
        at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.getData(TextEditorComponent.java:274)
        at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.getData(PsiAwareTextEditorImpl.java:118)
        at com.intellij.ide.impl.DataManagerImpl.getDataFromProvider(DataManagerImpl.java:81)
        at com.intellij.ide.impl.DataManagerImpl.getData(DataManagerImpl.java:69)
        at com.intellij.ide.impl.DataManagerImpl.access$300(DataManagerImpl.java:55)
        at com.intellij.ide.impl.DataManagerImpl$MyDataContext.doGetData(DataManagerImpl.java:391)
        at com.intellij.ide.impl.DataManagerImpl$MyDataContext.getData(DataManagerImpl.java:368)
        at com.intellij.openapi.actionSystem.DataContextWrapper.getData(DataContextWrapper.java:38)
        at com.intellij.openapi.actionSystem.AnActionEvent$1.getData(AnActionEvent.java:145)
        at com.intellij.openapi.actionSystem.DataKey.getData(DataKey.java:75)
        at com.intellij.ide.actions.ExternalJavaDocAction.update(ExternalJavaDocAction.java:144)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:122)
        at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:188)
        at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:139)
        at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:164)
        at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:164)
        at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:86)
        at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:280)
        at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:324)
        at com.intellij.openapi.actionSystem.impl.ActionMenu.access$600(ActionMenu.java:51)
        at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:278)
        at javax.swing.JMenu.fireMenuSelected(JMenu.java:1038)
        at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1118)
        at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:349)
        at javax.swing.DefaultButtonModel.setSelected(DefaultButtonModel.java:232)
        at javax.swing.JMenu.setSelected(JMenu.java:305)
        at javax.swing.JMenu.menuSelectionChanged(JMenu.java:1187)
        at com.intellij.openapi.actionSystem.impl.ActionMenu.menuSelectionChanged(ActionMenu.java:240)
        at javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:125)
        at javax.swing.plaf.basic.BasicMenuUI$Handler.mousePressed(BasicMenuUI.java:450)
        at java.awt.Component.processMouseEvent(Component.java:6530)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6298)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
        at java.awt.Container.dispatchEventImpl(Container.java:2280)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:675)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

~~~

**Comment by gregsh** [comment]
I've added some assertions to better understand the problem.
Please try the dev build and attach the new trace here.

https://teamcity.jetbrains.com/viewLog.html?buildId=952952&buildTypeId=IntellijIdeaPlugins_GrammarKit_Build&tab=artifacts

**Comment by azrdev** [comment]
@gregsh I'm running the dev build now, but could not reproduce the error. I'll follow-up here as soon as it happens again.
