### ISSUE TITLE
Generate Parser Code on the Command Line

### ISSUE THREAD

**Issue by kingsleyh** [JetBrains/Grammar-Kit#161]
Hi

In relation to Issue #34 

Any idea why this is not working - I don't understand what this missing extensionPoint is - any help greatly appreciated:

    GRAMMAR_KIT="/Users/hendrkin/Library/Application 
    Support/IntelliJIdea2017.1/GrammarKit/lib/grammar-kit.jar"
    LIB="/Applications/IntelliJ IDEA.app/Contents/lib/"
    GEN_DIR=src/main/gen
    BNF_FILE=src/main/java/net/kenro/ji/jin/purescript/grammar/Purescript.bnf
    java -cp "$GRAMMAR_KIT:$LIB/*:src/main" org.intellij.grammar.Main $GEN_DIR $BNF_FILE

causes exception:

    Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
    java.lang.IllegalArgumentException: Missing extension point: com.intellij.metaLanguage in area 
    null
	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:328)
	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:35)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:101)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:89)
	at com.intellij.lang.MetaLanguage.all(MetaLanguage.java:36)
	at com.intellij.lang.LanguageExtension.findForLanguage(LanguageExtension.java:76)
	at com.intellij.lang.LanguageExtension.forLanguage(LanguageExtension.java:59)
	at com.intellij.psi.impl.PsiFileFactoryImpl.trySetupPsiForFile(PsiFileFactoryImpl.java:114)
	at org.intellij.grammar.LightPsi$MyParsing.createFile(LightPsi.java:192)
	at org.intellij.grammar.LightPsi.parseFile(LightPsi.java:108)
	at org.intellij.grammar.LightPsi.parseFile(LightPsi.java:103)
	at org.intellij.grammar.Main.main(Main.java:64)

**Comment by hurricup** [comment]
Looks like an old grammar kit version. Looks like fixed in https://github.com/JetBrains/Grammar-Kit/commit/ce133e2eeec28be0f6748e206f8f1cecb0ea2f24

**Comment by kingsleyh** [comment]
Great thanks - I downloaded the latest from the releases page and its working now :)
