### ISSUE TITLE
ClassCastException in JobLauncher

### ISSUE THREAD

**Issue by tadfisher** [JetBrains/Grammar-Kit#216]
Using Idea IC-2019.1, GrammarKit 2019.1.1, and the Gradle GrammarKit plugin 2019.2.1.

Appears to have been caused by https://github.com/JetBrains/Grammar-Kit/commit/04c80343587cbec0677ea2c4f6c2aca582f5c7a6, which no longer sets `MockApplicationEx` in ApplicationManager, causing `JobLauncher` methods to fail when it casts `MockApplication` to `ApplicationEx`.

```
java.lang.ClassCastException: com.intellij.mock.MockApplication cannot be cast to com.intellij.openapi.application.ex.ApplicationEx
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:57)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.bulkProcessElementsWithWord(PsiSearchHelperImpl.java:204)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processSingleRequest(PsiSearchHelperImpl.java:957)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processRequests(PsiSearchHelperImpl.java:617)
	at com.intellij.psi.search.SearchRequestQuery.processResults(SearchRequestQuery.java:31)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:66)
	at com.intellij.util.MergeQuery.processSubQuery(MergeQuery.java:70)
	at com.intellij.util.MergeQuery.forEach(MergeQuery.java:43)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:55)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:45)
	at com.intellij.util.UniqueResultsQuery.findAll(UniqueResultsQuery.java:68)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcNextInner(BnfFirstNextAnalyzer.java:152)
	at org.intellij.grammar.analysis.BnfFirstNextAnalyzer.calcNext(BnfFirstNextAnalyzer.java:98)
	at org.intellij.grammar.generator.RuleGraphHelper.getRulesToTheLeft(RuleGraphHelper.java:506)
	at org.intellij.grammar.generator.RuleGraphHelper.buildRulesGraph(RuleGraphHelper.java:340)
	at org.intellij.grammar.generator.RuleGraphHelper.<init>(RuleGraphHelper.java:236)
	at org.intellij.grammar.generator.RuleGraphHelper.<init>(RuleGraphHelper.java:229)
	at org.intellij.grammar.generator.RuleGraphHelper.lambda$getCached$2(RuleGraphHelper.java:223)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$0(CachedValueBase.java:236)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:116)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at org.intellij.grammar.generator.RuleGraphHelper.getCached(RuleGraphHelper.java:225)
	at org.intellij.grammar.generator.ParserGenerator.<init>(ParserGenerator.java:200)
	at org.intellij.grammar.Main.main(Main.java:85)
```

**Comment by ice1000** [comment]
Happens for me as well

**Comment by gregsh** [comment]
Obsolete.
