### ISSUE TITLE
Grammar-Kit freezes the IDE!!

### ISSUE THREAD

**Issue by ice1000** [JetBrains/Grammar-Kit#234]
I have this from the error reporter:

```
 java.lang.Thread.run 62500ms
  java.util.concurrent.ThreadPoolExecutor$Worker.run 62500ms
   java.util.concurrent.ThreadPoolExecutor.runWorker 62500ms
    java.util.concurrent.CompletableFuture$AsyncSupply.run 62500ms
     com.intellij.openapi.progress.impl.ProgressRunner$$Lambda$926/0x0000000100d33840.get 62500ms
      com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4 62500ms
       com.intellij.openapi.progress.impl.CoreProgressManager.runProcess 62500ms
        com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress 62500ms
         com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress 62500ms
          com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun 62500ms
           com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$295/0x000000010039a840.run 62500ms
            com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2 62500ms
             com.intellij.openapi.progress.impl.ProgressRunner$$Lambda$930/0x0000000100d32840.run 62500ms
              com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3 62500ms
               com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1608/0x00000001013ce840.apply 62500ms
                com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5 62500ms
                 com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run 62500ms
                  org.intellij.grammar.actions.GenerateAction$1.run 62500ms
                   org.intellij.grammar.actions.GenerateAction$1.runInner 62500ms
                    com.intellij.openapi.project.DumbService.runReadActionInSmartMode 62500ms
                     com.intellij.openapi.application.ReadAction.compute 62500ms
                      com.intellij.openapi.application.impl.ApplicationImpl.runReadAction 62500ms
                       com.intellij.openapi.project.DumbService$$Lambda$3486/0x0000000102081440.compute 62500ms
                        com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1 62500ms
                         org.intellij.grammar.actions.GenerateAction$1$$Lambda$6394/0x0000000103207040.run 62500ms
                          org.intellij.grammar.actions.GenerateAction$1.lambda$runInner$0 62500ms
                           org.intellij.grammar.generator.ParserGenerator.generate 62500ms
                            org.intellij.grammar.generator.ParserGenerator.generatePsiImpl 62500ms
                             org.intellij.grammar.generator.ParserGeneratorUtil.getEffectiveSuperRule 55600ms
                              com.intellij.util.containers.JBIterable.last 55500ms
                               com.intellij.util.containers.JBIterator.hasNext 50800ms
                                com.intellij.util.containers.JBIterator.peekNext 50800ms
                                 com.intellij.util.containers.JBIterable$2$1.nextImpl 48100ms
                                  org.intellij.grammar.generator.ParserGeneratorUtil$1.fun 48000ms
                                   org.intellij.grammar.generator.ParserGeneratorUtil.getAttribute 33900ms
                                    org.intellij.grammar.generator.ParserGeneratorUtil.getAttribute 33900ms
                                     org.intellij.grammar.psi.impl.BnfFileImpl.findAttributeValue 32400ms
                                      com.intellij.util.containers.JBIterator.hasNext 23400ms
                                       com.intellij.util.containers.JBIterator.peekNext 23400ms
                                        com.intellij.util.containers.JBIterator$MapOp.apply 18600ms
                                         org.intellij.grammar.psi.impl.BnfFileImpl$$Lambda$3633/0x0000000102132c40.fun 18600ms
                                          org.intellij.grammar.psi.impl.BnfFileImpl.lambda$getMatchingAttributes$1 17800ms
                                           java.util.regex.Matcher.matches 14300ms
                                            java.util.regex.Matcher.match 14300ms
                                             java.util.regex.Pattern$CharPropertyGreedy.match 14300ms
                                              java.util.regex.Pattern$Slice.match 4300ms
                                              java.lang.Character.codePointAt 4000ms
                                              java.lang.Character.codePointBefore 2000ms
                                           java.util.regex.Pattern.matcher 3500ms
                                            java.util.regex.Matcher.<init> 3500ms
                                             java.util.regex.Matcher.reset 3500ms
                                              java.util.regex.Matcher.getTextLength 3500ms
                                        com.intellij.util.containers.JBIterator$FilterOp.apply 1900ms
                                        com.intellij.util.containers.JBIterable$2$1.nextImpl 1200ms
                                      org.intellij.grammar.psi.impl.BnfFileImpl.getMatchingAttributes 5100ms
                                       gnu.trove.THashMap.get 1800ms
                                        gnu.trove.TObjectHash.index 1800ms
                                         gnu.trove.TObjectHash.computeHashCode 400ms
                                       com.intellij.psi.impl.source.tree.TreeElement.getTextRange 900ms
                                        com.intellij.psi.impl.source.tree.TreeElement.getStartOffset 900ms
                                       java.util.Collections.binarySearch 600ms
                                        java.util.Collections.indexedBinarySearch 600ms
                                      com.intellij.util.containers.JBIterable$Intercepted.iterator 2300ms
                                       com.intellij.util.Functions$2.fun 2300ms
                                     com.intellij.psi.impl.source.tree.CompositePsiElement.getContainingFile 1000ms
                                      com.intellij.psi.impl.source.tree.SharedImplUtil.getContainingFile 1000ms
                                       com.intellij.psi.impl.source.tree.SharedImplUtil.findFileElement 900ms
                                   org.intellij.grammar.generator.RuleGraphHelper.getSynonymTargetOrSelf 10300ms
                                    org.intellij.grammar.generator.ParserGeneratorUtil.getAttribute 10300ms
                                     org.intellij.grammar.generator.ParserGeneratorUtil.getAttribute 10300ms
                                      org.intellij.grammar.psi.impl.BnfFileImpl.findAttributeValue 6700ms
                                       org.intellij.grammar.psi.impl.BnfFileImpl.getMatchingAttributes 6400ms
                                        gnu.trove.THashMap.get 2600ms
                                         gnu.trove.TObjectHash.index 2600ms
                                          gnu.trove.TObjectHash.computeHashCode 800ms
                                      com.intellij.psi.impl.source.tree.CompositePsiElement.getContainingFile 3600ms
                                       com.intellij.psi.impl.source.tree.SharedImplUtil.getContainingFile 3600ms
                                        com.intellij.psi.impl.source.tree.SharedImplUtil.findFileElement 3200ms
                                   java.util.HashSet.add 1500ms
                                    java.util.HashMap.put 1500ms
                                     java.util.HashMap.putVal 1500ms
                                   org.intellij.grammar.psi.impl.BnfFileImpl.getRule 1200ms
                                 com.intellij.util.containers.JBIterator$MapOp.apply 1600ms
                               com.intellij.util.containers.JBIterable$Intercepted.iterator 4700ms
                             org.intellij.grammar.generator.ParserGeneratorUtil.getAttribute 4400ms
                              org.intellij.grammar.generator.ParserGeneratorUtil.getAttribute 4400ms
                               org.intellij.grammar.psi.impl.BnfFileImpl.findAttributeValue 2400ms
                                org.intellij.grammar.psi.impl.BnfFileImpl.getMatchingAttributes 2300ms
                                 gnu.trove.THashMap.get 900ms
                                  gnu.trove.TObjectHash.index 900ms
                                   gnu.trove.TObjectHash.computeHashCode 200ms
                               com.intellij.psi.impl.source.tree.CompositePsiElement.getContainingFile 1700ms
                                com.intellij.psi.impl.source.tree.SharedImplUtil.getContainingFile 1700ms
                                 com.intellij.psi.impl.source.tree.SharedImplUtil.findFileElement 1500ms
                                 com.intellij.psi.impl.source.tree.CompositeElement.getPsi 200ms
                                  com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled 200ms
                                   com.intellij.openapi.progress.ProgressManager.checkCanceled 200ms
                             org.intellij.grammar.generator.ParserGenerator.ruleInfo 1300ms
                              java.util.TreeMap.get 1100ms
                               java.util.TreeMap.getEntry 1100ms
 java.awt.EventDispatchThread.run 100ms
  java.awt.EventDispatchThread.pumpEvents 100ms
   java.awt.EventDispatchThread.pumpEvents 100ms
    java.awt.EventDispatchThread.pumpEventsForHierarchy 100ms
     java.awt.EventDispatchThread.pumpEventsForFilter 100ms
      java.awt.EventDispatchThread.pumpOneEventForFilters 100ms
       com.intellij.ide.IdeEventQueue.dispatchEvent 100ms
        com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread 100ms
         com.intellij.ide.IdeEventQueue$$Lambda$502/0x00000001005c5840.run 100ms
          com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9 100ms
           com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized 100ms
            com.intellij.ide.IdeEventQueue$$Lambda$504/0x00000001005c4040.compute 100ms
             com.intellij.ide.IdeEventQueue.lambda$null$8 100ms
              com.intellij.ide.IdeEventQueue._dispatchEvent 100ms
               com.intellij.ide.IdeEventQueue.dispatchKeyEvent 100ms
                com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent 100ms
                 com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState 100ms
                  com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke 100ms
                   com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction 100ms
                    com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction 100ms
                     com.intellij.openapi.application.TransactionGuardImpl.performUserActivity 100ms
                      com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$$Lambda$3138/0x0000000101db0c40.run 100ms
                       com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3 100ms
                        com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction 100ms
                         com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware 100ms
                          com.intellij.ide.actions.UndoRedoAction.actionPerformed 100ms
                           com.intellij.ide.actions.UndoAction.perform 100ms
                            com.intellij.openapi.command.impl.UndoManagerImpl.undo 100ms
                             com.intellij.openapi.command.impl.UndoManagerImpl.undoOrRedo 100ms
                              com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand 100ms
                               com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand 100ms
                                com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand 100ms
                                 com.intellij.openapi.command.impl.UndoManagerImpl$$Lambda$4162/0x00000001027df840.run 100ms
                                  com.intellij.openapi.command.impl.UndoManagerImpl.lambda$undoOrRedo$0 100ms
                                   com.intellij.openapi.command.impl.CommandMerger.undoOrRedo 100ms
                                    com.intellij.openapi.command.impl.UndoRedo.execute 100ms
                                     com.intellij.openapi.command.impl.Undo.performAction 100ms
                                      com.intellij.openapi.command.impl.UndoableGroup.undo 100ms
                                       com.intellij.openapi.command.impl.UndoableGroup.undoOrRedo 100ms
                                        com.intellij.openapi.command.impl.UndoableGroup.doUndoOrRedo 100ms
                                         com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction 100ms
                                          com.intellij.openapi.application.impl.ApplicationImpl.startWrite 100ms
                                           com.intellij.openapi.application.impl.ReadMostlyRWLock.writeLock 100ms
                                            com.intellij.openapi.application.impl.ReadMostlyRWLock.areAllReadersIdle 100ms
                                             com.intellij.util.containers.LockFreeCopyOnWriteArrayList.iterator 100ms
```

I'll post the link to the grammar that hacks it soon.

**Comment by ice1000** [comment]
The stacktrace:

```
Freeze for 70 seconds
IDE KILLED! Sampled time: 62600ms, sampling rate: 100ms, GC time: 3090ms (4%), Class loading: 0%

The stack is from the thread that was blocking EDT

com.intellij.diagnostic.Freeze
	at org.intellij.grammar.psi.impl.BnfFileImpl.findAttributeValue(BnfFileImpl.java:94)
	at org.intellij.grammar.generator.ParserGeneratorUtil.getAttribute(ParserGeneratorUtil.java:166)
	at org.intellij.grammar.generator.ParserGeneratorUtil.getAttribute(ParserGeneratorUtil.java:157)
	at org.intellij.grammar.generator.ParserGeneratorUtil$1.fun(ParserGeneratorUtil.java:456)
	at com.intellij.util.containers.JBIterable$2$1.nextImpl(JBIterable.java:127)
	at com.intellij.util.containers.JBIterator.peekNext(JBIterator.java:150)
	at com.intellij.util.containers.JBIterator.hasNext(JBIterator.java:110)
	at com.intellij.util.containers.JBIterable.last(JBIterable.java:583)
	at org.intellij.grammar.generator.ParserGeneratorUtil.getEffectiveSuperRule(ParserGeneratorUtil.java:470)
	at org.intellij.grammar.generator.ParserGenerator.generatePsiImpl(ParserGenerator.java:1762)
	at org.intellij.grammar.generator.ParserGenerator.generate(ParserGenerator.java:415)
	at org.intellij.grammar.actions.GenerateAction$1.lambda$runInner$0(GenerateAction.java:172)
	at org.intellij.grammar.actions.GenerateAction$1$$Lambda$6394/0x0000000103207040.run(Unknown Source)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:150)
	at com.intellij.openapi.project.DumbService$$Lambda$3486/0x0000000102081440.compute(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:898)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:143)
	at org.intellij.grammar.actions.GenerateAction$1.runInner(GenerateAction.java:160)
	at org.intellij.grammar.actions.GenerateAction$1.run(GenerateAction.java:128)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:930)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:432)
	at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1608/0x00000001013ce840.apply(Unknown Source)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.ProgressRunner$$Lambda$930/0x0000000100d32840.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$295/0x000000010039a840.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.ProgressRunner$$Lambda$926/0x0000000100d33840.get(Unknown Source)
	at java.base@11.0.6/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base@11.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base@11.0.6/java.lang.Thread.run(Thread.java:834)
```

**Comment by ice1000** [comment]
Ah, probably it's because of recursive `extends` relation.

**Comment by ice1000** [comment]
I solve the problem by removing infinitely-recursive `extends` relation, but it's sensible to add such error-handling to Grammar-Kit

**Comment by gregsh** [comment]
@ice1000 There's some guard against that, so it's no easily reproducible.
Can you provide the snippet to reproduce the problem, please?

**Comment by ice1000** [comment]
https://github.com/owo-lang/intellij-dtlc/blob/4021c4c189a380fabeb25338ba16f514851a506a/lang/miniagda.bnf
and
https://github.com/owo-lang/intellij-dtlc/blob/504e8e3b975f062a2ab375556f5fc9acd417e57c/lang/miniagda.bnf

two revisions of the same file

**Comment by ice1000** [comment]
Cool!
