### ISSUE TITLE
Error in IntelliJ 2020.1 BETA

### ISSUE THREAD

**Issue by rikvdkleij** [JetBrains/Grammar-Kit#236]
After a couple of times doing Generate parser code from a .bnf , I'm getting the below error for which the only solution works is to Invalidate the IntelliJ cache... (but this is of course very annoying because you will have to wait till the index is built again)

IntelliJ build 201.6668.12
Grammar-kit 2019.3

I also got a freeze for about 90 seconds but I will sent that one automatically to you,

```
com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.PsiClassImpl; no psi for file stub PsiJavaFileStub [intellij.haskell.psi], invalidation reason=onContentReload
	at com.intellij.psi.impl.source.SubstrateRef$StubRef.reportError(SubstrateRef.java:156)
	at com.intellij.psi.impl.source.SubstrateRef$StubRef.getContainingFile(SubstrateRef.java:148)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:253)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:134)
	at com.intellij.psi.impl.source.PsiClassImpl.getNode(PsiClassImpl.java:106)
	at com.intellij.psi.impl.source.PsiClassImpl.getNode(PsiClassImpl.java:40)
	at com.intellij.psi.PsiInvalidElementAccessException.getPsiInvalidationTrace(PsiInvalidElementAccessException.java:97)
	at com.intellij.psi.PsiInvalidElementAccessException.<init>(PsiInvalidElementAccessException.java:60)
	at com.intellij.psi.impl.source.SubstrateRef$StubRef.reportError(SubstrateRef.java:156)
	at com.intellij.psi.impl.source.SubstrateRef$StubRef.getContainingFile(SubstrateRef.java:148)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:253)
	at org.jetbrains.plugins.scala.lang.resolve.ResolveUtils$.isAccessibleWithNewModifiers(ResolveUtils.scala:107)
	at org.jetbrains.plugins.scala.lang.resolve.ResolveUtils$.isAccessible(ResolveUtils.scala:84)
	at org.jetbrains.plugins.scala.lang.resolve.processor.ResolveProcessor.isAccessible(ResolveProcessor.scala:109)
	at org.jetbrains.plugins.scala.lang.resolve.processor.ResolveProcessor.execute(ResolveProcessor.scala:117)
	at org.jetbrains.plugins.scala.lang.resolve.processor.BaseProcessor.execute(BaseProcessor.scala:70)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScPackageImpl$.packageProcessDeclarations(ScPackageImpl.scala:178)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScPackageImpl.processDeclarations(ScPackageImpl.scala:55)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.imports.ScImportStmtImpl.workWithImportExpr$1(ScImportStmtImpl.scala:210)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.imports.ScImportStmtImpl.processDeclarations(ScImportStmtImpl.scala:342)
	at org.jetbrains.plugins.scala.lang.psi.ScImportsHolder.processDeclarations(ScImportsHolder.scala:58)
	at org.jetbrains.plugins.scala.lang.psi.ScImportsHolder.processDeclarations$(ScImportsHolder.scala:48)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.packaging.ScPackagingImpl.processDeclarations(ScPackagingImpl.scala:99)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.ScStableCodeReferenceImpl.treeWalkUp$1(ScStableCodeReferenceImpl.scala:287)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.ScStableCodeReferenceImpl.processQualifier(ScStableCodeReferenceImpl.scala:305)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.ScStableCodeReferenceImpl.doResolve(ScStableCodeReferenceImpl.scala:517)
	at org.jetbrains.plugins.scala.lang.resolve.StableCodeReferenceResolver.resolve(StableCodeReferenceResolver.scala:41)
	at org.jetbrains.plugins.scala.lang.resolve.ResolvableStableCodeReference$Ext$.liftedTree3$1(ResolvableStableCodeReference.scala:43)
	at org.jetbrains.plugins.scala.lang.resolve.ResolvableStableCodeReference$Ext$.resolveNoConstructor$extension(ResolvableStableCodeReference.scala:39)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.types.ScSimpleTypeElementImpl.innerNonValueType(ScSimpleTypeElementImpl.scala:277)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.types.ScSimpleTypeElementImpl.innerType(ScSimpleTypeElementImpl.scala:44)
	at org.jetbrains.plugins.scala.lang.psi.api.base.types.ScTypeElement.liftedTree1$1(ScTypeElement.scala:33)
	at org.jetbrains.plugins.scala.lang.psi.api.base.types.ScTypeElement.getType(ScTypeElement.scala:31)
	at org.jetbrains.plugins.scala.lang.psi.api.base.types.ScTypeElement.getType$(ScTypeElement.scala:31)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.types.ScSimpleTypeElementImpl.getType(ScSimpleTypeElementImpl.scala:42)
	at org.jetbrains.plugins.scala.lang.psi.api.base.types.ScTypeElement.type(ScTypeElement.scala:29)
	at org.jetbrains.plugins.scala.lang.psi.api.base.types.ScTypeElement.type$(ScTypeElement.scala:29)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.types.ScSimpleTypeElementImpl.type(ScSimpleTypeElementImpl.scala:42)
	at org.jetbrains.plugins.scala.lang.psi.impl.statements.params.ScParameterImpl.type(ScParameterImpl.scala:93)
	at org.jetbrains.plugins.scala.lang.psi.api.statements.params.ScParameter.getRealParameterType(ScParameter.scala:65)
	at org.jetbrains.plugins.scala.lang.psi.api.statements.params.ScParameter.getRealParameterType$(ScParameter.scala:64)
	at org.jetbrains.plugins.scala.lang.psi.impl.statements.params.ScParameterImpl.getRealParameterType(ScParameterImpl.scala:34)
	at org.jetbrains.plugins.scala.lang.psi.light.ScLightParameter$.javaParameterType(ScLightParameter.scala:64)
	at org.jetbrains.plugins.scala.lang.psi.light.ScLightParameter$.$anonfun$from$1(ScLightParameter.scala:45)
	at org.jetbrains.plugins.scala.lang.psi.light.ScLightParameter.getType(ScLightParameter.scala:23)
	at org.intellij.grammar.java.JavaHelper$PsiHelper.acceptsMethod(JavaHelper.java:227)
	at org.intellij.grammar.java.JavaHelper$PsiHelper.findClassMethods(JavaHelper.java:201)
	at org.intellij.grammar.generator.ParserGeneratorUtil.findRuleImplMethods(ParserGeneratorUtil.java:383)
	at org.intellij.grammar.generator.ParserGenerator.getRuleMethodTypesToImport(ParserGenerator.java:1903)
	at org.intellij.grammar.generator.ParserGenerator.generatePsiIntf(ParserGenerator.java:1727)
	at org.intellij.grammar.generator.ParserGenerator.generate(ParserGenerator.java:405)
	at org.intellij.grammar.actions.GenerateAction$1.lambda$runInner$0(GenerateAction.java:172)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:898)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:143)
	at org.intellij.grammar.actions.GenerateAction$1.runInner(GenerateAction.java:160)
	at org.intellij.grammar.actions.GenerateAction$1.run(GenerateAction.java:128)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:930)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:432)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by niktrop** [comment]
It should be fixed in Scala plugin now.

**Comment by rikvdkleij** [comment]
Thanks!
