### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/Hash$Strategy  while generating parser

### ISSUE THREAD

**Issue by BrianPin** [JetBrains/Grammar-Kit#247]
Hi

I happened to see this build failure when I switch to use new JetBrain sdk release 2020.2, (before it was fine).

it failed to build because the exception:

> Task :pegasusplugin:generatePdlParser FAILED
Exception in thread "main" java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/Hash$Strategy
        at com.intellij.core.CoreFileTypeRegistry.<init>(CoreFileTypeRegistry.java:23)
        at com.intellij.core.CoreApplicationEnvironment.<init>(CoreApplicationEnvironment.java:83)
        at com.intellij.core.CoreApplicationEnvironment.<init>(CoreApplicationEnvironment.java:74)
        at org.intellij.grammar.LightPsi$MyParsing.<init>(LightPsi.java:166)
        at org.intellij.grammar.LightPsi.<clinit>(LightPsi.java:65)
        at org.intellij.grammar.Main.main(Main.java:49)
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.Hash$Strategy
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 6 more
After I switch back to use 2020.1, it builds fine.

How should I solve this problem? Will it be necessary to have changes from JetBrain ?

This is happening while generate parse gradle task is running

**Comment by zxj5470** [comment]
As we all know Grammar-Kit has no 2020.2 version，so it may be compatible with JB-sdk 2020.2~
And I find there's no `intellij-deps-fastutil.jar` in 2020.1……
Just roll back to 2020.1 and wait for Grammar-Kit new release~

**Comment by karollewandowski** [comment]
Hi, any plans for this? Is there any workaround to develop against 2020.2 and 2020.3 soon?

**Comment by hurricup** [comment]
Are you using grammar-kit gradle plugin? Because I had no problems with 2020.2 and have no problems with 2020.3 there.
https://github.com/JetBrains/gradle-grammar-kit-plugin

**Comment by gregsh** [comment]
https://github.com/JetBrains/gradle-grammar-kit-plugin shall do.
