### ISSUE TITLE
`NoClassDefFoundError: com/intellij/psi/PsiModifierListOwner` after switching from 2020.3.1 to 12a20e0 

### ISSUE THREAD

**Issue by KMax** [JetBrains/Grammar-Kit#278]
After switching from 2020.3.1 to

```groovy
grammarKit {
    jflexRelease = '1.7.0-2'
    grammarKitRelease = '12a20e0'
}
```
my build started to fail with the following exception

```java
java.lang.NoClassDefFoundError: com/intellij/psi/PsiModifierListOwner
        at org.intellij.grammar.java.JavaHelper$AsmHelper$MySignatureVisitor.visitFormalTypeParameter(JavaHelper.java:829)
        at org.jetbrains.org.objectweb.asm.signature.SignatureReader.accept(SignatureReader.java:79)
        at org.intellij.grammar.java.JavaHelper$AsmHelper.getMethodInfo(JavaHelper.java:607)
        at org.intellij.grammar.java.JavaHelper$AsmHelper$MyClassVisitor.visitMethod(JavaHelper.java:673)
        at org.jetbrains.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1331)
        at org.jetbrains.org.objectweb.asm.ClassReader.accept(ClassReader.java:722)
        at org.jetbrains.org.objectweb.asm.ClassReader.accept(ClassReader.java:402)
        at org.intellij.grammar.java.JavaHelper$AsmHelper.getClassInfo(JavaHelper.java:596)
        at org.intellij.grammar.java.JavaHelper$AsmHelper.findClassSafe(JavaHelper.java:585)
        at org.intellij.grammar.java.JavaHelper$AsmHelper.getSuperClassName(JavaHelper.java:496)
        at org.intellij.grammar.generator.ParserGenerator.lambda$calcRealSuperClasses$2(ParserGenerator.java:285)
        at com.intellij.util.containers.FilteredTraverserBase$Meta.childrenImpl(FilteredTraverserBase.java:436)
        at com.intellij.util.containers.FilteredTraverserBase$Meta.children(FilteredTraverserBase.java:422)
        at com.intellij.util.containers.FilteredTraverserBase.children(FilteredTraverserBase.java:303)
        at com.intellij.util.containers.TreeTraversal$2$1WrappedTree.fun(TreeTraversal.java:121)
        at com.intellij.util.containers.TreeTraversal$2$1WrappedTree.fun(TreeTraversal.java:108)
        at com.intellij.util.containers.TreeTraversal$P.iterable(TreeTraversal.java:805)
        at com.intellij.util.containers.TreeTraversal$P.iterator(TreeTraversal.java:799)
        at com.intellij.util.containers.TreeTraversal$BiOrderIt.nextImpl(TreeTraversal.java:540)
        at com.intellij.util.containers.JBIterator.peekNext(JBIterator.java:150)
        at com.intellij.util.containers.JBIterator.hasNext(JBIterator.java:110)
        at com.intellij.util.containers.JBIterable$FlattenFun$FlattenIt.nextImpl(JBIterable.java:470)
        at com.intellij.util.containers.JBIterator.peekNext(JBIterator.java:150)
        at com.intellij.util.containers.JBIterator.hasNext(JBIterator.java:110)
        at com.intellij.util.containers.JBIterable.first(JBIterable.java:547)
        at com.intellij.util.containers.JBIterable.find(JBIterable.java:617)
        at org.intellij.grammar.generator.ParserGenerator.calcRealSuperClasses(ParserGenerator.java:286)
        at org.intellij.grammar.generator.ParserGenerator.generate(ParserGenerator.java:385)
        at org.intellij.grammar.Main.main(Main.java:73)
Caused by: java.lang.ClassNotFoundException: com.intellij.psi.PsiModifierListOwner
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 29 more
```

Any idea what could be the cause?

**Comment by hurricup** [comment]
What kind and version of IDE you are building against?

**Comment by KMax** [comment]
> What kind and version of IDE you are building against?

It's IntelliJ IDEA Community 211-EAP-SNAPSHOT

**Comment by gregsh** [comment]
Also https://github.com/JetBrains/gradle-grammar-kit-plugin/issues/48
