### ISSUE TITLE
IJ 2021.2 - Getting `java.lang.ClassNotFoundException: dk.brics.automaton.AutomatonProvider`

### ISSUE THREAD

**Issue by takanuva15** [JetBrains/Grammar-Kit#283]
Hi, I'm trying to update my plugin which uses GrammarKit to support IJ 2021.2, but when I set the intellij plugin version to `PC-2021.2` and run the test Ide, it fails on the `GenerateParser` task and shows this error:
```
> Task :generateAhkParser
ASM not available, using reflection helper: java.lang.NoClassDefFoundError: org/jetbrains/org/objectweb/asm/signature/SignatureVisitor
WARN: Attempt to load key 'psi.incremental.reparse.depth.limit' for not yet loaded registry
java.lang.NoClassDefFoundError: dk/brics/automaton/AutomatonProvider
	at com.intellij.patterns.StandardPatterns.string(StandardPatterns.java:31)
	at org.intellij.grammar.psi.impl.BnfStringRefContributor.registerReferenceProviders(BnfStringRefContributor.java:46)
	at org.intellij.grammar.psi.impl.BnfStringImpl.<clinit>(BnfStringImpl.java:35)
	at org.intellij.grammar.psi.BnfTypes$Factory.createElement(BnfTypes.java:112)
	at org.intellij.grammar.BnfASTFactory.createComposite(BnfASTFactory.java:21)
	at com.intellij.lang.ASTFactory.composite(ASTFactory.java:66)
	at com.intellij.lang.impl.PsiBuilderImpl.createComposite(PsiBuilderImpl.java:1301)
	at com.intellij.lang.impl.PsiBuilderImpl.bind(PsiBuilderImpl.java:1214)
	at com.intellij.lang.impl.PsiBuilderImpl.buildTree(PsiBuilderImpl.java:906)
	at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:892)
	at org.intellij.grammar.parser.GrammarParser.parse(GrammarParser.java:21)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:58)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:53)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$2(LazyParseableElement.java:175)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:481)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:174)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:226)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:24)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:37)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:741)
	at com.intellij.psi.SyntaxTraverser$PsiApi.first(SyntaxTraverser.java:296)
	at com.intellij.psi.SyntaxTraverser$PsiApi.first(SyntaxTraverser.java:264)
	at com.intellij.psi.SyntaxTraverser$ApiEx.children(SyntaxTraverser.java:241)
	at com.intellij.psi.SyntaxTraverser$Api.fun(SyntaxTraverser.java:179)
	at com.intellij.psi.SyntaxTraverser$Api.fun(SyntaxTraverser.java:161)
	at com.intellij.util.containers.TreeTraversal$P.iterable(TreeTraversal.java:805)
	at com.intellij.util.containers.TreeTraversal$P.iterator(TreeTraversal.java:799)
	at com.intellij.util.containers.TreeTraversal$GuidedItImpl.nextImpl(TreeTraversal.java:757)
	at com.intellij.util.containers.JBIterator.peekNext(JBIterator.java:150)
	at com.intellij.util.containers.JBIterator.hasNext(JBIterator.java:110)
	at com.intellij.util.containers.TreeTraversal$P.iterator(TreeTraversal.java:800)
	at com.intellij.util.containers.TreeTraversal$BiOrderIt.nextImpl(TreeTraversal.java:540)
	at com.intellij.util.containers.JBIterator.peekNext(JBIterator.java:150)
	at com.intellij.util.containers.JBIterator.hasNext(JBIterator.java:110)
	at org.intellij.grammar.psi.impl.BnfFileImpl.calcAttributeValues(BnfFileImpl.java:171)
	at org.intellij.grammar.psi.impl.BnfFileImpl$1.compute(BnfFileImpl.java:205)
	at com.intellij.openapi.util.ClearableLazyValue.getValue(ClearableLazyValue.java:39)
	at com.intellij.openapi.util.AtomicClearableLazyValue.getValue(AtomicClearableLazyValue.java:9)
	at org.intellij.grammar.psi.impl.BnfFileImpl.getMatchingAttributes(BnfFileImpl.java:112)
	at org.intellij.grammar.psi.impl.BnfFileImpl.findAttributeValue(BnfFileImpl.java:82)
	at org.intellij.grammar.generator.ParserGeneratorUtil.getRootAttribute(ParserGeneratorUtil.java:136)
	at org.intellij.grammar.generator.ParserGeneratorUtil.getRootAttribute(ParserGeneratorUtil.java:132)
	at org.intellij.grammar.generator.GenOptions.<init>(GenOptions.java:40)
	at org.intellij.grammar.generator.ParserGenerator.<init>(ParserGenerator.java:170)
	at org.intellij.grammar.Main.main(Main.java:73)
Caused by: java.lang.ClassNotFoundException: dk.brics.automaton.AutomatonProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 45 more
```

Relevant snippets in my `build.gradle.kts`:
```kts
plugins {
    id("org.jetbrains.grammarkit") version "2021.1.1"
}
...
intellij {
    version = "2021.2"
    type = "PC"
    setPlugins("com.github.b3er.idea.plugins.arc.browser:0.23")
}
...
```
The full build file is viewable [here](https://github.com/Nordgedanken/intellij-autohotkey/blob/main/build.gradle.kts)

**Comment by takanuva15** [comment]
Ok never mind, I think I figured it out. I should have been using the latest grammar-kit version 2021.1.3. The error is gone now
