### ISSUE TITLE
NoClassDefFoundError: org/apache/velocity/runtime/log/NullLogChute in 2023.2

### ISSUE THREAD

**Issue by jreznot** [JetBrains/Grammar-Kit#331]
IntelliJ IDEA 2023.2 EAP (Ultimate Edition)
Build #IU-232.3318, built on March 31, 2023

Non-Bundled Plugins:
    org.jetbrains.idea.grammar (2022.3.1)

```
java.lang.NoClassDefFoundError: org/apache/velocity/runtime/log/NullLogChute
	at org.intellij.grammar.actions.BnfGenerateLexerAction.generateLexerText(BnfGenerateLexerAction.java:166)
	at org.intellij.grammar.actions.BnfGenerateLexerAction.lambda$actionPerformed$1(BnfGenerateLexerAction.java:104)
	at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$4(WriteCommandAction.java:360)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$1(WriteCommandAction.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:972)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$2(WriteCommandAction.java:147)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:184)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.doRunWriteCommandAction(WriteCommandAction.java:156)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:123)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:360)
	at org.intellij.grammar.actions.BnfGenerateLexerAction.actionPerformed(BnfGenerateLexerAction.java:97)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:333)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:307)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:356)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:307)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$5(ActionMenuItem.java:300)
```

**Comment by gregsh** [comment]
On 17.03.2023 Velocity 1.7 was suddenly updated to 2.3... I see.
