### ISSUE TITLE
Generate Parser Code on Command Line.

### ISSUE THREAD

**Issue by carymrobbins** [JetBrains/Grammar-Kit#34]
How are you supposed to generate parser code on the command line?  It looks like issue #4 indicates this is possible, however, I'm not sure how to apply it.  It seems that I am supposed to indicate a class path.

``` bash
JAR=~/Library/Application\ Support/IdeaIC13/GrammarKit/lib/grammar-kit.jar
BNF=src/com/haskforce/Haskell.bnf
GEN=gen
java -jar $JAR $BNF $GEN
```

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/intellij/lang/ParserDefinition                          │cli-parser-1.1.jar                 jna-utils.jar                      resources_en.jar
        at java.lang.Class.getDeclaredMethods0(Native Method)                                                          │commons-codec-1.8.jar              jna.jar                            rhino-js-1_7R4.jar
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2531)                                                  │commons-httpclient-3.1-patched.jar jps-launcher.jar                   rngom-20051226-patched.jar
        at java.lang.Class.getMethod0(Class.java:2774)                                                                 │commons-logging-1.1.1.jar          jps-server.jar                     rt
        at java.lang.Class.getMethod(Class.java:1663)                                                                  │commons-net-3.1.jar                jsch-0.1.50.jar                    sanselan-0.98-snapshot.jar
        at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)                                          │ecj-4.2.1.jar                      jsr166e.jar                        serviceMessages.jar
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)                                       │extensions.jar                     jsr173_1.0_api.jar                 snappy-java-1.0.5.jar
Caused by: java.lang.ClassNotFoundException: com.intellij.lang.ParserDefinition                                        │forms_rt.jar                       junit-4.10.jar                     swingx-core-1.6.2.jar
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)                                                      │grammar-kit.jar                    junit.jar                          trang-core.jar
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)                                                      │groovy                             jzlib-1.1.1.jar                    trove4j.jar
        at java.security.AccessController.doPrivileged(Native Method)                                                  │groovy-all-2.0.6.jar               libpty                             trove4j_src.jar
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)                                                  │gson-2.2.3.jar                     log4j.jar                          util.jar
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)                                                       │guava-14.0.1.jar                   markdownj-core-0.4.2-SNAPSHOT.jar  velocity.jar
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)                                               │icons.jar                          microba.jar                        winp-1.17-patched.jar
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)                                                       │idea.jar                           miglayout-swing.jar                xbean.jar
        ... 6 more
```

**Comment by kingsleyh** [comment]
Hi

Any idea why this is not working - I don't understand what this missing extensionPoint is - any help greatly appreciated:

    GRAMMAR_KIT="/Users/hendrkin/Library/Application 
    Support/IntelliJIdea2017.1/GrammarKit/lib/grammar-kit.jar"
    LIB="/Applications/IntelliJ IDEA.app/Contents/lib/"
    GEN_DIR=src/main/gen
    BNF_FILE=src/main/java/net/kenro/ji/jin/purescript/grammar/Purescript.bnf
    java -cp "$GRAMMAR_KIT:$LIB/*:src/main" org.intellij.grammar.Main $GEN_DIR $BNF_FILE

causes exception:

    Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
    java.lang.IllegalArgumentException: Missing extension point: com.intellij.metaLanguage in area 
    null
	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:328)
	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:35)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:101)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:89)
	at com.intellij.lang.MetaLanguage.all(MetaLanguage.java:36)
	at com.intellij.lang.LanguageExtension.findForLanguage(LanguageExtension.java:76)
	at com.intellij.lang.LanguageExtension.forLanguage(LanguageExtension.java:59)
	at com.intellij.psi.impl.PsiFileFactoryImpl.trySetupPsiForFile(PsiFileFactoryImpl.java:114)
	at org.intellij.grammar.LightPsi$MyParsing.createFile(LightPsi.java:192)
	at org.intellij.grammar.LightPsi.parseFile(LightPsi.java:108)
	at org.intellij.grammar.LightPsi.parseFile(LightPsi.java:103)
	at org.intellij.grammar.Main.main(Main.java:64)
